name: Build docs
on:
  push:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  python-version: "3.11"
  plone-version: "6.0-latest"

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3

      # Setup Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Setup Plone and Python
      - name: Setup Plone ${{ env.plone-version }} with Python ${{ env.python-version }}
        id: setup
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ env.python-version }}
          plone-version: ${{ env.plone-version }}

      # Install plone.distribution and the requirements for documentation
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-docs.txt

      # Build the documentation
      - name: Build Documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      # Upload artifact to pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_build/html'

      # Deploy to GitHub pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
